import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import Sidebar from "@/components/Sidebar";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-spartan",
});

export const metadata: Metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${leagueSpartan.variable} font-sans antialiased`}>
        <Provider>
          <Sidebar />
          <main className="md:ml-25.75 p-6">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}